const CountryCodes = [
  { name: "Afghanistan",                                  iso: "af", alt: [] },
  { name: "Aland Islands ! Åland Islands",                iso: "ax", alt: [] },
  { name: "Albania",                                      iso: "al", alt: [] },
  { name: "Algeria",                                      iso: "dz", alt: [] },
  { name: "American Samoa",                               iso: "as", alt: [] },
  { name: "Andorra",                                      iso: "ad", alt: [] },
  { name: "Angola",                                       iso: "ao", alt: [] },
  { name: "Anguilla",                                     iso: "ai", alt: [] },
  { name: "Antarctica",                                   iso: "aq", alt: [] },
  { name: "Antigua and Barbuda",                          iso: "ag", alt: [] },
  { name: "Argentina",                                    iso: "ar", alt: [] },
  { name: "Armenia",                                      iso: "am", alt: [] },
  { name: "Aruba",                                        iso: "aw", alt: [] },
  { name: "Australia",                                    iso: "au", alt: [] },
  { name: "Austria",                                      iso: "at", alt: [] },
  { name: "Azerbaijan",                                   iso: "az", alt: [] },
  { name: "Bahamas",                                      iso: "bs", alt: [] },
  { name: "Bahrain",                                      iso: "bh", alt: [] },
  { name: "Bangladesh",                                   iso: "bd", alt: [] },
  { name: "Barbados",                                     iso: "bb", alt: [] },
  { name: "Belarus",                                      iso: "by", alt: [] },
  { name: "Belgium",                                      iso: "be", alt: [] },
  { name: "Belize",                                       iso: "bz", alt: [] },
  { name: "Benin",                                        iso: "bj", alt: [] },
  { name: "Bermuda",                                      iso: "bm", alt: [] },
  { name: "Bhutan",                                       iso: "bt", alt: [] },
  { name: "Bolivia, Plurinational State of",              iso: "bo", alt: [] },
  { name: "Bosnia and Herzegovina",                       iso: "ba", alt: [] },
  { name: "Botswana",                                     iso: "bw", alt: [] },
  { name: "Bouvet Island",                                iso: "bv", alt: [] },
  { name: "Brazil",                                       iso: "br", alt: [] },
  { name: "British Indian Ocean Territory",               iso: "io", alt: [] },
  { name: "Brunei Darussalam",                            iso: "bn", alt: [] },
  { name: "Bulgaria",                                     iso: "bg", alt: [] },
  { name: "Burkina Faso",                                 iso: "bf", alt: [] },
  { name: "Burundi",                                      iso: "bi", alt: [] },
  { name: "Cambodia",                                     iso: "kh", alt: [] },
  { name: "Cameroon",                                     iso: "cm", alt: [] },
  { name: "Canada",                                       iso: "ca", alt: [] },
  { name: "Cape Verde",                                   iso: "cv", alt: [] },
  { name: "Cayman Islands",                               iso: "ky", alt: [] },
  { name: "Central African Republic",                     iso: "cf", alt: [] },
  { name: "Chad",                                         iso: "td", alt: [] },
  { name: "Chile",                                        iso: "cl", alt: [] },
  { name: "China",                                        iso: "cn", alt: [] },
  { name: "Christmas Island",                             iso: "cx", alt: [] },
  { name: "Cocos (Keeling) Islands",                      iso: "cc", alt: [] },
  { name: "Colombia",                                     iso: "co", alt: [] },
  { name: "Comoros",                                      iso: "km", alt: [] },
  { name: "Congo",                                        iso: "cg", alt: [] },
  { name: "Congo, the Democratic Republic of the",        iso: "cd", alt: [] },
  { name: "Cook Islands",                                 iso: "ck", alt: [] },
  { name: "Costa Rica",                                   iso: "cr", alt: [] },
  { name: "Cote d'Ivoire ! Côte d'Ivoire",                iso: "ci", alt: [] },
  { name: "Croatia",                                      iso: "hr", alt: [] },
  { name: "Cuba",                                         iso: "cu", alt: [] },
  { name: "Cyprus",                                       iso: "cy", alt: [] },
  { name: "Czech Republic",                               iso: "cz", alt: [] },
  { name: "Denmark",                                      iso: "dk", alt: [] },
  { name: "Djibouti",                                     iso: "dj", alt: [] },
  { name: "Dominica",                                     iso: "dm", alt: [] },
  { name: "Dominican Republic",                           iso: "do", alt: [] },
  { name: "Ecuador",                                      iso: "ec", alt: [] },
  { name: "Egypt",                                        iso: "eg", alt: [] },
  { name: "El Salvador",                                  iso: "sv", alt: [] },
  { name: "Equatorial Guinea",                            iso: "gq", alt: [] },
  { name: "Eritrea",                                      iso: "er", alt: [] },
  { name: "Estonia",                                      iso: "ee", alt: [] },
  { name: "Ethiopia",                                     iso: "et", alt: [] },
  { name: "Falkland Islands (Malvinas",                   iso: "fk", alt: [] },
  { name: "Faroe Islands",                                iso: "fo", alt: [] },
  { name: "Fiji",                                         iso: "fj", alt: [] },
  { name: "Finland",                                      iso: "fi", alt: [] },
  { name: "France",                                       iso: "fr", alt: [] },
  { name: "French Guiana",                                iso: "gf", alt: [] },
  { name: "French Polynesia",                             iso: "pf", alt: [] },
  { name: "French Southern Territories",                  iso: "tf", alt: [] },
  { name: "Gabon",                                        iso: "ga", alt: [] },
  { name: "Gambia",                                       iso: "gm", alt: [] },
  { name: "Georgia",                                      iso: "ge", alt: [] },
  { name: "Germany",                                      iso: "de", alt: [] },
  { name: "Ghana",                                        iso: "gh", alt: [] },
  { name: "Gibraltar",                                    iso: "gi", alt: [] },
  { name: "Greece",                                       iso: "gr", alt: [] },
  { name: "Greenland",                                    iso: "gl", alt: [] },
  { name: "Grenada",                                      iso: "gd", alt: [] },
  { name: "Guadeloupe",                                   iso: "gp", alt: [] },
  { name: "Guam",                                         iso: "gu", alt: [] },
  { name: "Guatemala",                                    iso: "gt", alt: [] },
  { name: "Guernsey",                                     iso: "gg", alt: [] },
  { name: "Guinea",                                       iso: "gn", alt: [] },
  { name: "Guinea-Bissau",                                iso: "gw", alt: [] },
  { name: "Guyana",                                       iso: "gy", alt: [] },
  { name: "Haiti",                                        iso: "ht", alt: [] },
  { name: "Heard Island and McDonald Islands",            iso: "hm", alt: [] },
  { name: "Holy See (Vatican City State",                 iso: "va", alt: [] },
  { name: "Honduras",                                     iso: "hn", alt: [] },
  { name: "Hong Kong",                                    iso: "hk", alt: [] },
  { name: "Hungary",                                      iso: "hu", alt: [] },
  { name: "Iceland",                                      iso: "is", alt: [] },
  { name: "India",                                        iso: "in", alt: [] },
  { name: "Indonesia",                                    iso: "id", alt: [] },
  { name: "Iran, Islamic Republic of",                    iso: "ir", alt: [] },
  { name: "Iraq",                                         iso: "iq", alt: [] },
  { name: "Ireland",                                      iso: "ie", alt: [] },
  { name: "Isle of Man",                                  iso: "im", alt: [] },
  { name: "Israel",                                       iso: "il", alt: [] },
  { name: "Italy",                                        iso: "it", alt: [] },
  { name: "Jamaica",                                      iso: "jm", alt: [] },
  { name: "Japan",                                        iso: "jp", alt: [] },
  { name: "Jersey",                                       iso: "je", alt: [] },
  { name: "Jordan",                                       iso: "jo", alt: [] },
  { name: "Kazakhstan",                                   iso: "kz", alt: [] },
  { name: "Kenya",                                        iso: "ke", alt: [] },
  { name: "Kiribati",                                     iso: "ki", alt: [] },
  { name: "Korea, Democratic People's Republic of",       iso: "kp", alt: [] },
  { name: "Korea, Republic of",                           iso: "kr", alt: [] },
  { name: "Kuwait",                                       iso: "kw", alt: [] },
  { name: "Kyrgyzstan",                                   iso: "kg", alt: [] },
  { name: "Lao People's Democratic Republic",             iso: "la", alt: [] },
  { name: "Latvia",                                       iso: "lv", alt: [] },
  { name: "Lebanon",                                      iso: "lb", alt: [] },
  { name: "Lesotho",                                      iso: "ls", alt: [] },
  { name: "Liberia",                                      iso: "lr", alt: [] },
  { name: "Libyan Arab Jamahiriya",                       iso: "ly", alt: [] },
  { name: "Liechtenstein",                                iso: "li", alt: [] },
  { name: "Lithuania",                                    iso: "lt", alt: [] },
  { name: "Luxembourg",                                   iso: "lu", alt: [] },
  { name: "Macao",                                        iso: "mo", alt: [] },
  { name: "Macedonia, the former Yugoslav Republic of",   iso: "mk", alt: [] },
  { name: "Madagascar",                                   iso: "mg", alt: [] },
  { name: "Malawi",                                       iso: "mw", alt: [] },
  { name: "Malaysia",                                     iso: "my", alt: [] },
  { name: "Maldives",                                     iso: "mv", alt: [] },
  { name: "Mali",                                         iso: "ml", alt: [] },
  { name: "Malta",                                        iso: "mt", alt: [] },
  { name: "Marshall Islands",                             iso: "mh", alt: [] },
  { name: "Martinique",                                   iso: "mq", alt: [] },
  { name: "Mauritania",                                   iso: "mr", alt: [] },
  { name: "Mauritius",                                    iso: "mu", alt: [] },
  { name: "Mayotte",                                      iso: "yt", alt: [] },
  { name: "Mexico",                                       iso: "mx", alt: [] },
  { name: "Micronesia, Federated States of",              iso: "fm", alt: [] },
  { name: "Moldova, Republic of",                         iso: "md", alt: [] },
  { name: "Monaco",                                       iso: "mc", alt: [] },
  { name: "Mongolia",                                     iso: "mn", alt: [] },
  { name: "Montenegro",                                   iso: "me", alt: [] },
  { name: "Montserrat",                                   iso: "ms", alt: [] },
  { name: "Morocco",                                      iso: "ma", alt: [] },
  { name: "Mozambique",                                   iso: "mz", alt: [] },
  { name: "Myanmar",                                      iso: "mm", alt: [] },
  { name: "Namibia",                                      iso: "na", alt: [] },
  { name: "Nauru",                                        iso: "nr", alt: [] },
  { name: "Nepal",                                        iso: "np", alt: [] },
  { name: "Netherlands",                                  iso: "nl", alt: [] },
  { name: "Netherlands Antilles",                         iso: "an", alt: [] },
  { name: "New Caledonia",                                iso: "nc", alt: [] },
  { name: "New Zealand",                                  iso: "nz", alt: [] },
  { name: "Nicaragua",                                    iso: "ni", alt: [] },
  { name: "Niger",                                        iso: "ne", alt: [] },
  { name: "Nigeria",                                      iso: "ng", alt: [] },
  { name: "Niue",                                         iso: "nu", alt: [] },
  { name: "Norfolk Island",                               iso: "nf", alt: [] },
  { name: "Northern Mariana Islands",                     iso: "mp", alt: [] },
  { name: "Norway",                                       iso: "no", alt: [] },
  { name: "Oman",                                         iso: "om", alt: [] },
  { name: "Pakistan",                                     iso: "pk", alt: [] },
  { name: "Palau",                                        iso: "pw", alt: [] },
  { name: "Palestinian Territory, Occupied",              iso: "ps", alt: [] },
  { name: "Panama",                                       iso: "pa", alt: [] },
  { name: "Papua New Guinea",                             iso: "pg", alt: [] },
  { name: "Paraguay",                                     iso: "py", alt: [] },
  { name: "Peru",                                         iso: "pe", alt: [] },
  { name: "Philippines",                                  iso: "ph", alt: [] },
  { name: "Pitcairn",                                     iso: "pn", alt: [] },
  { name: "Poland",                                       iso: "pl", alt: [] },
  { name: "Portugal",                                     iso: "pt", alt: [] },
  { name: "Puerto Rico",                                  iso: "pr", alt: [] },
  { name: "Qatar",                                        iso: "qa", alt: [] },
  { name: "Reunion ! Réunion",                            iso: "re", alt: [] },
  { name: "Romania",                                      iso: "ro", alt: [] },
  { name: "Russian Federation",                           iso: "ru", alt: [] },
  { name: "Rwanda",                                       iso: "rw", alt: [] },
  { name: "Saint Barthélemy",                             iso: "bl", alt: [] },
  { name: "Saint Helena, Ascension and Tristan da Cunha", iso: "sh", alt: [] },
  { name: "Saint Kitts and Nevis",                        iso: "kn", alt: [] },
  { name: "Saint Lucia",                                  iso: "lc", alt: [] },
  { name: "Saint Martin (French part",                    iso: "mf", alt: [] },
  { name: "Saint Pierre and Miquelon",                    iso: "pm", alt: [] },
  { name: "Saint Vincent and the Grenadines",             iso: "vc", alt: [] },
  { name: "Samoa",                                        iso: "ws", alt: [] },
  { name: "San Marino",                                   iso: "sm", alt: [] },
  { name: "Sao Tome and Principe",                        iso: "st", alt: [] },
  { name: "Saudi Arabia",                                 iso: "sa", alt: [] },
  { name: "Senegal",                                      iso: "sn", alt: [] },
  { name: "Serbia",                                       iso: "rs", alt: [] },
  { name: "Seychelles",                                   iso: "sc", alt: [] },
  { name: "Sierra Leone",                                 iso: "sl", alt: [] },
  { name: "Singapore",                                    iso: "sg", alt: [] },
  { name: "Slovakia",                                     iso: "sk", alt: [] },
  { name: "Slovenia",                                     iso: "si", alt: [] },
  { name: "Solomon Islands",                              iso: "sb", alt: [] },
  { name: "Somalia",                                      iso: "so", alt: [] },
  { name: "South Africa",                                 iso: "za", alt: [] },
  { name: "South Georgia and the South Sandwich Islands", iso: "gs", alt: [] },
  { name: "Spain",                                        iso: "es", alt: [] },
  { name: "Sri Lanka",                                    iso: "lk", alt: [] },
  { name: "Sudan",                                        iso: "sd", alt: [] },
  { name: "Suriname",                                     iso: "sr", alt: [] },
  { name: "Svalbard and Jan Mayen",                       iso: "sj", alt: [] },
  { name: "Swaziland",                                    iso: "sz", alt: [] },
  { name: "Sweden",                                       iso: "se", alt: [] },
  { name: "Switzerland",                                  iso: "ch", alt: [] },
  { name: "Syrian Arab Republic",                         iso: "sy", alt: [] },
  { name: "Taiwan, Province of China",                    iso: "tw", alt: [] },
  { name: "Tajikistan",                                   iso: "tj", alt: [] },
  { name: "Tanzania, United Republic of",                 iso: "tz", alt: [] },
  { name: "Thailand",                                     iso: "th", alt: [] },
  { name: "Timor-Leste",                                  iso: "tl", alt: [] },
  { name: "Togo",                                         iso: "tg", alt: [] },
  { name: "Tokelau",                                      iso: "tk", alt: [] },
  { name: "Tonga",                                        iso: "to", alt: [] },
  { name: "Trinidad and Tobago",                          iso: "tt", alt: [] },
  { name: "Tunisia",                                      iso: "tn", alt: [] },
  { name: "Turkey",                                       iso: "tr", alt: [] },
  { name: "Turkmenistan",                                 iso: "tm", alt: [] },
  { name: "Turks and Caicos Islands",                     iso: "tc", alt: [] },
  { name: "Tuvalu",                                       iso: "tv", alt: [] },
  { name: "Uganda",                                       iso: "ug", alt: [] },
  { name: "Ukraine",                                      iso: "ua", alt: [] },
  { name: "United Arab Emirates",                         iso: "ae", alt: [] },
  { name: "United Kingdom",                               iso: "gb", alt: [] },
  { name: "United States",                                iso: "us", alt: [] },
  { name: "United States Minor Outlying Islands",         iso: "um", alt: [] },
  { name: "Uruguay",                                      iso: "uy", alt: [] },
  { name: "Uzbekistan",                                   iso: "uz", alt: [] },
  { name: "Vanuatu",                                      iso: "vu", alt: [] },
  { name: "Venezuela, Bolivarian Republic of",            iso: "ve", alt: [] },
  { name: "Viet Nam",                                     iso: "vn", alt: [] },
  { name: "Virgin Islands, British",                      iso: "vg", alt: [] },
  { name: "Virgin Islands, U.S",                          iso: "vi", alt: [] },
  { name: "Wallis and Futuna",                            iso: "wf", alt: [] },
  { name: "Western Sahara",                               iso: "eh", alt: [] },
  { name: "Yemen",                                        iso: "ye", alt: [] },
  { name: "Zambia",                                       iso: "zm", alt: [] },
  { name: "Zimbabwe",                                     iso: "zw", alt: [] }];
